name: bootpay_webview_flutter
description: bootpay_webview_flutter 를 국내 결제환경에 맞게 fork 떠서 관리하는 프로젝트 입니다.
repository: https://github.com/bootpay/bootpay_webview_flutter
issue_tracker: https://github.com/bootpay/bootpay_webview_flutter/issues
version: 4.12.0

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: bootpay_webview_flutter_android
      ios:
        default_package: bootpay_webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
  bootpay_webview_flutter_android: ^4.10.5
  bootpay_webview_flutter_platform_interface: ^2.14.0
  bootpay_webview_flutter_wkwebview: ^3.23.21
#  webview_flutter: ^4.10.0


dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  plugin_platform_interface: ^2.1.7
